plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
}

android {
    namespace 'io.core.engine'
    compileSdk 36

    defaultConfig {
        minSdk 24
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "proguard-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    kotlin {
        jvmToolchain(11)
        kotlinOptions {
            freeCompilerArgs = ['-Xjvm-default=all-compatibility']
        }
    }

    buildFeatures {
        viewBinding true
        dataBinding true
    }
}

dependencies {
    api project(':modules:core-ui')
    
    api libs.refresh.layout.kernel
    api libs.refresh.header.material
    api libs.refresh.footer.classics
    api libs.flexbox
    
    compileOnly libs.mmkv
    compileOnly libs.glide
    compileOnly libs.room.ktx
    ksp libs.room.compiler
    
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
