ext {
    fyNamespace = 'io.core.kits'
    fyViewBinding = true
    fyDataBinding = true
}

apply from: '../fy-library.gradle'
apply from: '../fy-publish.gradle'

apply plugin: 'com.google.devtools.ksp'

android {
    sourceSets {
        main {
            res.srcDirs(
                    'src/main/res',
            )
        }
    }
}

dependencies {

    // FyCore 2.0 子模块依赖
    api project(':modules:fy-kernel')
    api project(':modules:fy-utils')
    api project(':modules:fy-event')
    api project(':modules:fy-storage')
    api project(':modules:fy-validation')
    api project(':modules:fy-shape')
    api project(':modules:fy-widget')
    api project(':modules:fy-ui')

    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    api libs.annotations
    api libs.google.gson
    api libs.activity.ktx
    api libs.recyclerview
    api libs.preference.ktx
    api libs.lifecycle.livedata.ktx
    api libs.lifecycle.viewmodel.ktx
    api libs.lifecycle.runtime.ktx
    api libs.lifecycle.service
    api libs.lifecycle.process
    api libs.navigation.fragment.ktx
    api libs.navigation.ui.ktx
    api libs.kotlinx.serialization.json
    implementation libs.flexbox
    implementation libs.kotlin.reflect
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    compileOnly libs.room.ktx
    ksp libs.room.compiler

    // MMKV
    compileOnly libs.mmkv
    // Glide
    compileOnly(libs.glide)

    // https://github.com/gyf-dev/ImmersionBar
    api libs.immersionbar
    api libs.immersionbar.ktx
}
