// custom-maven.gradle
allprojects {
    repositories {
        maven {
            credentials {
                username '63d4d579378edb0fd9aa3b2d'
                password 'nXJxEWiiObre'
            }
            url 'https://packages.aliyun.com/67789758cdfeb44ae202deb7/maven/2512815-release-ndmhzu'
        }
    }
}