plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}

android {
    namespace 'com.core.fy.android'
    compileSdk 33

    defaultConfig {
        applicationId "com.core.libraries"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {

    //implementation 'com.github.yuantris:FyCore:0.0.1'
    implementation libs.fycore
    //implementation project(':core_feature')

    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // 动画解析库：https://github.com/airbnb/lottie-android
    // 动画资源：https://lottiefiles.com、https://icons8.com/animated-icons
    implementation libs.lottie

    implementation libs.room.ktx
    kapt libs.room.compiler
    annotationProcessor libs.room.compiler
}

//configurations.configureEach {
//    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
//        def requested = details.requested
//        if (requested.group == 'org.jetbrains.kotlin') {
//            if (requested.name.startsWith("kotlin")) {
//                details.useVersion libs.versions.kotlin.version
//            }
//        }
//    }
//}