plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
}

android {
    namespace 'com.core.fy.android'
    compileSdk 34

    defaultConfig {
        applicationId "com.core.fy.android"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures {
        viewBinding true
    }
}

// 选择依赖版本
// libs.versions.local.get()  本地模块
// libs.versions.jitpack.get() GitHub Jitpack版本
// libs.versions.package.get() GitHub package版本
def version = libs.versions.local.get()

ext {
    fycoreDependencies = [
            jitpack: libs.fycore.github,
            package: libs.fycore.git.package,
            local : project(':core_feature')
    ]
}

dependencies {

    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation(libs.flexbox)
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation fycoreDependencies[version]


    implementation libs.room.ktx
    //noinspection KaptUsageInsteadOfKsp
    kapt libs.room.compiler
    annotationProcessor libs.room.compiler

    //media
    implementation(libs.media.media)
    // For media playback using ExoPlayer
    implementation(libs.media3.exoplayer)
    // For exposing and controlling media sessions
    //implementation "androidx.media3:media3-session:$media3_version"

    //Glide
    implementation(libs.glide)

    // https://github.com/liangjingkanji/BRV
    implementation (libs.brv) {
        exclude group: 'com.github.liangjingkanji', module: 'StateLayout'
    }

    // 动画解析库：https://github.com/airbnb/lottie-android
    // 动画资源：https://lottiefiles.com、https://icons8.com/animated-icons
    implementation libs.lottie
    implementation libs.xxpermissions

    // https://github.com/gyf-dev/ImmersionBar
    implementation libs.immersionbar
    implementation libs.immersionbar.ktx

    // https://github.com/Blankj/AndroidUtilCode
    implementation libs.utilcodex

    // ShapeView：https://github.com/getActivity/ShapeView
    implementation libs.shapeView
    // ShapeDrawable：https://github.com/getActivity/ShapeDrawable
    implementation libs.shapedrawable
}
