apply plugin: 'AndResGuard'
android {
    andResGuard {
        mappingFile = file("./resource_mapping.txt")
        mappingFile = null
        use7zip = false
        useSign = true
        // it will keep the origin path of your resources when it's true
        keepRoot = false
//        //是否启用代码加固（默认false，请在info.json[0].jiagu处配置）
//        useJiaGu = true
//        //加固application名称（默认com.stub.StubApp）
//        jgName = null
//        //加固使用密码（默认使用包名、签名MD5计算）
//        jgPsd = null
//        //是否删除混淆临时文件（默认true）
//        delOutDir = true
//        //输出apk名称（默认release_%s.apk）
//        moveApkName = null
//        //输出apk文件夹（默认初始文件夹）
//        moveApkFolder = null

        whiteList = [
                // your icon
                "R.mipmap.icon",

                // your properties
                "R.id.iv_test_again",
                "R.id.iv_net_diagnosis",
                "R.id.calendar",
                "R.id.rv_week",
                "R.id.progress_bar",
                "R.id.tv_progress",
                "R.id.tv_unit",
                "R.id.iv_again",
                "R.id.tv_device_num",
                "R.id.unknown_num",
                "R.id.known_num",
                "R.id.tv_wifi_name_final",
                "R.id.iv_img",
                "R.id.view_center",
                "R.id.tv_wifi_name",
                "R.id.detect_view",
                "R.id.iv_detect",
                "R.id.et_pwd",
                "R.id.tip_pwd",
                "R.id.iv_copy",
                "R.id.pwd_bottom_line",
                "R.id.tip_tag",
                "R.id.rv_tag",
                "R.id.iv_save",
                "R.id.iv_edit_exit",
                "R.id.tv_delete",
                "R.id.cb_check",
                "R.id.tv_all_pick",
                "R.id.iv_line",
                "R.id.rv_month",
                "R.id.iv_tips_2",
                "R.id.rv_list",
                "R.id.iv_tips_1",
                "R.id.cl_result",
                "R.id.iv_test_again",
                "R.id.iv_net_diagnosis",
                "R.id.cl_content",
                "R.id.iv_icon",
                "R.id.chart1",
                "R.id.chart_day",
                "R.id.ll_ing_down",
                "R.id.chart2",
                "R.id.ll_ing_up",
                "R.id.dividing_line",
                "R.id.start_velocity",
                "R.id.tv_download",
                "R.id.tv_upload",
                "R.id.iv_download_icon",
                "R.id.tv_final_down",
                "R.id.tv_final_upload",
                "R.id.iv_download_icon2",
                "R.id.iv_upload_icon2",
                "R.id.chart1_final",
                "R.id.chart2_final",
                "R.id.iv_upload_icon",
                "R.id.scrollView",
                "R.id.fl_container",
                //隔空投送
                "R.id.iv_header_btn",
                "R.id.tv_progress",

        ]
        compressFilePattern = [
                "*.png",
                "*.jpg",
                "*.jpeg",
                "*.gif",
                "*.xml",

                "resources.arsc"
        ]
        sevenzip {
            artifact = 'com.zy.sdk.res.guard:SevenZip:1.6.00'
            //path = "/usr/local/bin/7za"
        }

    }
}

