plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}

android {
    namespace 'com.core.libraries'
    compileSdk 34

    defaultConfig {
        minSdk 24

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "proguard-rules.pro"
    }

    sourceSets {
        main {
            // res 资源目录配置
            res.srcDirs(
                    'src/main/res',
                    'src/main/res-dimen',
            )
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures {
        viewBinding true
        dataBinding true
    }

}


dependencies {

    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    api libs.activity.ktx
    api libs.lifecycle.livedata.ktx
    api libs.lifecycle.viewmodel.ktx
    api libs.lifecycle.runtime.ktx
    implementation libs.kotlin.reflect

    implementation libs.room.ktx
    kapt libs.room.compiler
    annotationProcessor libs.room.compiler

    // https://github.com/gyf-dev/ImmersionBar
    api libs.immersionbar
    api libs.immersionbar.ktx

    // https://github.com/Blankj/AndroidUtilCode
    api libs.utilcodex
    // 标题栏框架：https://github.com/getActivity/TitleBar
    // api 'com.github.getActivity:TitleBar:10.5'

    // ShapeView：https://github.com/getActivity/ShapeView
    api libs.shapeView
    // ShapeDrawable：https://github.com/getActivity/ShapeDrawable
    api libs.shapedrawable
}